<DialogContent>:
	orientation: "vertical"
    spacing: "6dp"
    size_hint_y: None
#    adaptive_height:True
    height: dp(350)

	Image:
		id: image
#        size_hint_y: .9
#        keep_ratio: True
        size_hint: (1, 0.9)
#        allow_stretch: True
#        width: dp(60)
#        width: self.parent.width
#		height: self.parent.width/self.image_ratio
		size: self.texture_size
        source: app.currentImage

	MDLabel:
		text: app.dialogText
		size_hint: (1, 0.1)
