<Toolbar>:
	md_bg_color: app.theme_cls.primary_color
	background_palette: "Primary"
	background_hue: "500"
	elevation: 10
#	right_action_items: [["information-outline", lambda x: app.showHint(self.parent.name)]]
	left_action_items: [["menu", lambda x: app.root.ids.navigationDrawer.set_state("open")], ["arrow-left", lambda x: app.openScreen("home")]]
	pos_hint: {"top": 1}


<Hint>:
	type: "two-line"
    text: app.hintText
    left_action: ["CANCEL", lambda x: None]
